# Generated by Django 5.0.9 on 2024-12-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcode_cu', models.CharField(max_length=15, unique=True)),
                ('ean_cu', models.CharField(max_length=13, null=True)),
                ('root_pd_id', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=15)),
                ('groupname', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=1)),
                ('shelf_life', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_CU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rus_definition', models.TextField()),
                ('eng_definition', models.TextField()),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_Definitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50)),
                ('ownership', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_Suppliers',
                'managed': False,
            },
        ),
    ]
