# Generated by Django 5.0.9 on 2024-12-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('diameter', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('net_weight', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_CU_Dimensions',
                'managed': False,
            },
        ),
    ]
