# Generated by Django 5.0.9 on 2024-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0002_cudimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcode_tu', models.CharField(max_length=15, unique=True)),
                ('ean_cu', models.CharField(max_length=13, null=True)),
                ('category', models.CharField(max_length=15)),
                ('groupname', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=5)),
                ('type', models.CharField(max_length=1)),
                ('shelf_life', models.SmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_CU',
                'managed': False,
            },
        ),
    ]
