# Generated by Django 5.0.9 on 2024-12-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0003_tu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tu',
            table='ROOT_REF_SKU_TU',
        ),
    ]
