# Generated by Django 5.0.9 on 2024-12-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0004_alter_tu_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('composition_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_Compositions',
                'managed': False,
            },
        ),
    ]
