# Generated by Django 4.2.15 on 2025-03-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0005_composition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=3)),
                ('description_text', models.TextField()),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_TU_Descriptions',
                'managed': False,
            },
        ),
    ]
