# Generated by Django 4.2.15 on 2025-03-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0006_tudescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuCustomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_code', models.CharField(max_length=10)),
                ('duty', models.FloatField(null=True)),
                ('okpd2_code', models.CharField(max_length=10)),
                ('vat', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_CU_Customs_info',
                'managed': False,
            },
        ),
    ]
