# Generated by Django 4.2.15 on 2025-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0007_cucustomsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('net_weight', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_TU_Dimensions',
                'managed': False,
            },
        ),
    ]
