# Generated by Django 4.2.15 on 2025-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0008_tudimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuLogisticsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_per_layer', models.IntegerField(null=True)),
                ('layers_per_pal', models.IntegerField(null=True)),
                ('pal_per_truck', models.IntegerField(null=True)),
                ('gross_weight_pal', models.FloatField(null=True)),
                ('gross_weight_tu', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_TU_Logistics_info',
                'managed': False,
            },
        ),
    ]
