# Generated by Django 4.2.15 on 2025-04-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0009_tulogisticsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuOrderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moq', models.FloatField(null=True)),
                ('order_inc', models.FloatField(null=True)),
                ('is_shared', models.CharField(max_length=15, null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_TU_Order_info',
                'managed': False,
            },
        ),
    ]
