# Generated by Django 4.2.15 on 2025-04-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0010_tuorderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcode_mix', models.CharField(max_length=15, unique=True)),
                ('ean_mix', models.CharField(max_length=14, null=True)),
                ('category', models.CharField(max_length=15)),
                ('groupname', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=5)),
                ('mix_in_box', models.IntegerField()),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_MIX',
                'managed': False,
            },
        ),
    ]
