# Generated by Django 4.2.15 on 2025-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0011_mix'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ROOT_REF_SKU_MIX_Compositions',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Composition',
        ),
    ]
