# Generated by Django 5.0.14 on 2025-06-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_service', '0012_mixcomposition_delete_composition'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cu',
            table='[00_ROOT].[ROOT_REF_SKU_CU]',
        ),
        migrations.AlterModelTable(
            name='cucustomsinfo',
            table='[00_ROOT].[ROOT_REF_SKU_CU_Customs_info]',
        ),
        migrations.AlterModelTable(
            name='cudimensions',
            table='[00_ROOT].[ROOT_REF_SKU_CU_Dimensions]',
        ),
        migrations.AlterModelTable(
            name='definition',
            table='[00_ROOT].[ROOT_REF_SKU_Definitions]',
        ),
        migrations.AlterModelTable(
            name='mix',
            table='[00_ROOT].[ROOT_REF_SKU_MIX]',
        ),
        migrations.AlterModelTable(
            name='mixcomposition',
            table='[00_ROOT].[ROOT_REF_SKU_MIX_Compositions]',
        ),
        migrations.AlterModelTable(
            name='supplier',
            table='[00_ROOT].[ROOT_REF_SKU_Suppliers]',
        ),
        migrations.AlterModelTable(
            name='tu',
            table='[00_ROOT].[ROOT_REF_SKU_TU]',
        ),
        migrations.AlterModelTable(
            name='tudescription',
            table='[00_ROOT].[ROOT_REF_SKU_TU_Descriptions]',
        ),
        migrations.AlterModelTable(
            name='tudimensions',
            table='[00_ROOT].[ROOT_REF_SKU_TU_Dimensions]',
        ),
        migrations.AlterModelTable(
            name='tulogisticsinfo',
            table='[00_ROOT].[ROOT_REF_SKU_TU_Logistics_info]',
        ),
        migrations.AlterModelTable(
            name='tuorderinfo',
            table='[00_ROOT].[ROOT_REF_SKU_TU_Order_info]',
        ),
    ]
