from django.urls import path
from .views import ref_sku_views

urlpatterns = [
    path('', ref_sku_views.main_page),
    path('ref_sku/', ref_sku_views.ref_sku),
    path('cu/<int:cu_id>/', ref_sku_views.cu_page, name='show_cu'),
    path('cu/create/', ref_sku_views.cu_creation_page, name='cu_create'),
    path('cu/create/save/', ref_sku_views.cu_creation_page_save, name='cu_create_save'),
    path('cu/<int:cu_id>/save/', ref_sku_views.cu_page_save, name='save_cu'),
    path('cu/<int:cu_id>/save-dimensions/', ref_sku_views.cu_page_save_dimensions, name='save_cu_dimensions'),
    path('cu/<int:cu_id>/save-supplier/', ref_sku_views.cu_page_save_supplier, name='save_cu_supplier'),
    path('cu/get-supplier-info/', ref_sku_views.cu_page_get_supplier_info, name='cu_page_get_supplier_info'),
    path('cu/<int:cu_id>/save-customs_info/', ref_sku_views.cu_page_save_customs_info, name='save_cu_customs_info'),
    path('tu/<int:tu_id>/', ref_sku_views.tu_page, name='show_tu'),
    path('tu/create/', ref_sku_views.tu_creation_page, name='tu_create'),
    path('tu/create/save/', ref_sku_views.tu_creation_page_save, name='tu_create_save'),
    path('tu/<int:tu_id>/save/', ref_sku_views.tu_page_save, name='save_tu'),
    path('tu/<int:tu_id>/save-descriptions/', ref_sku_views.tu_page_save_descriptions, name='save_tu_descriptions'),
    path('tu/<int:tu_id>/save-dimensions/', ref_sku_views.tu_page_save_dimensions, name='save_tu_dimensions'),
    path('tu/<int:tu_id>/save-logistics_info/', ref_sku_views.tu_page_save_logistics_info, name='save_tu_logistics_info'),
    path('tu/<int:tu_id>/save-order_info/', ref_sku_views.tu_page_save_order_info, name='save_tu_order_info'),
    path('mix/<int:mix_id>/', ref_sku_views.mix_page, name='show_mix'),
    path('mix/create/', ref_sku_views.mix_creation_page, name='mix_create'),
    path('mix/create/save/', ref_sku_views.mix_creation_page_save, name='mix_create_save'),
    path('mix/<int:mix_id>/save/', ref_sku_views.mix_page_save, name='save_mix'),
    path('mix/<int:mix_id>/save-compositions/', ref_sku_views.mix_page_save_compositions, name='save_mix_compositions'),
    path('mix/<int:mix_id>/save-dimensions/', ref_sku_views.mix_page_save_dimensions, name='save_mix_dimensions'),
    path('mix/<int:mix_id>/save-logistics_info/', ref_sku_views.mix_page_save_logistics_info, name='save_mix_logistics_info'),
    path('mix/<int:mix_id>/save-customs_info/', ref_sku_views.mix_page_save_customs_info, name='save_mix_customs_info'),
    path('mix/<int:mix_id>/save-descriptions/', ref_sku_views.mix_page_save_descriptions, name='save_mix_descriptions'),
    path('cu/<int:cu_id>/set-classification/', ref_sku_views.cu_set_classification, name='cu_set_classification'),
    path('mix/<int:mix_id>/set-classification/', ref_sku_views.mix_set_classification, name='mix_set_classification'),
]
