# Generated by Django 5.0.14 on 2025-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KG_TMP_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_year', models.CharField(max_length=255)),
                ('date_month', models.CharField(max_length=255)),
                ('store_kg', models.CharField(max_length=255)),
                ('rus_description', models.CharField(max_length=255)),
                ('measure_name', models.CharField(max_length=255)),
                ('measure_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '[11_KG].[KG_TMP_Sales]',
                'managed': False,
            },
        ),
    ]
