# Generated by Django 5.0.14 on 2025-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KG_PIVOT_SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.TextField()),
                ('is_last_upload', models.BooleanField()),
            ],
            options={
                'db_table': '[11_KG].[KG_PIVOT_SKU]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KG_REF_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_kg', models.TextField()),
                ('chain', models.TextField()),
                ('type', models.TextField()),
            ],
            options={
                'db_table': '[11_KG].[KG_REF_Stores]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KG_TMP_Competitor_Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_year', models.CharField(max_length=255)),
                ('date_month', models.CharField(max_length=255)),
                ('store_kg', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('measure_name', models.CharField(max_length=255)),
                ('measure_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': '[11_KG].[KG_TMP_Competitors_sales]',
                'managed': False,
            },
        ),
    ]
